### ISSUE TITLE
No wake up Packet

### ISSUE THREAD

**Issue by BillSavage042** [streetpea/chiaki4deck#113]
When I try to access my PS5 from "game mode" on an outside network, it no longer gives me the option to send a wake up packet.  I have to go to desktop mode, right click and send wake up packet, then go to game mode and start the remote play.  Is there a way to manually send a wake up packet in game mode on the deck?

**Comment by streetpea** [comment]
If you have to right click and send a wake-up packet it sounds like you registered your device manually but it isn't being discovered by the discovery manager. You should still be able to right-click in game mode but would have to set a shortcut to do that easily since the controller profile doesn't have right click in it like the desktop controller profile does. However, I would advise skipping that process entirely since it is quite cumbersome and instead using the automation you can setup following the instructions here: https://streetpea.github.io/chiaki4deck/setup/automation/

**Comment by outcoldman** [comment]
@streetpea it is a little bit confusing about the automation mode, so you can create this script, what is after that, how that would help to automatically wake up the PS5 from the game mode?

**Comment by streetpea** [comment]
So there is a creation script that will create a script for you that wakes up your ps5 and then launches into Chiaki4deck. This process is explained in this section: https://streetpea.github.io/chiaki4deck/setup/automation/.

Then, you add the script as a non-Steam game in game mode following this section: https://streetpea.github.io/chiaki4deck/setup/steaming/.

Then when you launch the chiaki4deck non-Steam game in game mode you are launching the script which automates the wake-up and connection so you don't have to launch Chiaki4deck directly and launch using the ui.

**Comment by outcoldman** [comment]
@streetpea that makes sense! Curious, why that cannot be implemented within the application / GUI itself? I am sure a lot of users like me are very confused with those steps.

**Comment by BillSavage042** [comment]
I never knew you had to add the sh to steam, which seems dumb now that I think of it.  Ive ran that script so many times in the past and just thought it didnt work.  Thank you!

**Comment by streetpea** [comment]
@outcoldman there's actually a pr open #109 to add the shortcut to Steam directly via the gui so it'll likely get easier very soon
