### ISSUE TITLE
Controller profiles not appearing

### ISSUE THREAD

**Issue by natcl** [streetpea/chiaki4deck#13]
When I go in the community controller profiles and try searching for the ones you mention in the documentation, I can’t seem to find it. Do you have an idea why it wouldn’t appear ?
I have a feeling I see the profiles for chiaki but not chiaki4deck.
Thanks !

**Comment by streetpea** [comment]
It’s based on the name you put for the game in Steam. You need to use chiaki4deck as the name of the game in Steam for the controller profiles to come up (bc that’s what i used). This is how Steam handles non-steam game controller profiles (it associates them by name since there is no game id to use). I’m adding this to the guide for the upcoming release (just need to finish up the documentation updates). I’ll keep this issue so people can see the solution before the documentation update comes out and I can track the update. For now, just rename the app entry to chiaki4deck in the properties of the app in Steam. Once you do this. You can download the profile and make a template out of it that you can use if you either want to change the name of the game or create a copy of the game with another name (I.e, you have a version for you and a family member or different ones for different PlayStation console and have a script for each). 

Also fyi, I will be slightly updating the default configuration for the upcoming release (later this week once the documentation is done being updated) to enable you to use either the touchscreen or the right touchpad for native ps touchpad support (the gestures in addition to the button clicks). Note: of course you can also use the same setting on the left touchpad for but I won’t be adding that to the default config.

**Comment by natcl** [comment]
Thanks that was the issue indeed !
Thanks a lot for your great work !

**Comment by streetpea** [comment]
Your welcome ... the documentation is now updated in the latest release here: https://streetpea.github.io/chiaki4deck/setup/controlling/#retrieving-chiaki4deck-controller-layouts-when-using-an-alternate-game-name-most-users-can-skip-this to address this (why I closed the issue).
