### ISSUE TITLE
Addition of haptics for Steam Deck streaming from PS5

### ISSUE THREAD

**Issue by ejleslie** [streetpea/chiaki4deck#14]
Currently when streaming from PS5, there is no rumble feedback on the Steam Deck; if this is something that could be added, it would be a big boost to the gameplay feel for a lot of titles.

(As mentioned in https://github.com/streetpea/chiaki4deck/issues/6 where I initially brought it up, there is also no haptic feedback on the DualSense controller when streaming from PS5, which is also true in the original chiaki on all platforms. Since this is a Steam Deck focused branch I didn't think about it, but hey, if it can be done? Rad. I'm sure folks playing on the Deck with a paired DualSense would appreciate it.)

**Comment by streetpea** [comment]
Thanks for adding the issue. I will definitely look into this.

**Comment by jbaiter** [comment]
This would be incredible, even if only for DualSense controllers connected to the deck. But I think it's going to require some reverse engineering, since the current Takion protocol definitions in chiaki have nothing related to haptics.

Supporting it for attached DualSense controllers is probably going to require somework as well, since Sony's kernel driver does not support haptics, and neither does the Kernel API for controllers.

However, from what I could find so far, Haptics on the DualSense seems to be implemented using audio data, i.e. the controller haptics function as a kind of speaker and haptic effects are sent as waveforms. See for example this PoC Windows implementation:
https://gist.github.com/Ohjurot/b0c04dfbd25fb71bc0da50947d313d1b
Maybe this means that if the hapticis data comes in as a PCM or compressed audio stream from the PlayStation, we could simply send it to the DualSense Audio device?

So tasks involved in this seem  to be:
- Reverse Engineer Takion protocol to find out if and how it passes haptics data to clients
- Find out how to process the haptics data to map to the Steamworks [`TriggerHapticPulse`](https://partner.steamgames.com/doc/api/isteaminput#TriggerHapticPulse)/[`TriggerRepeatedHapticPulse`](https://partner.steamgames.com/doc/api/isteaminput#TriggerRepeatedHapticPulse)/[`TriggerVibration`](https://partner.steamgames.com/doc/api/isteaminput#TriggerVibration) APIs or native Linux APIs (implementing it via Steamworks probably means no Flatpak?)
- Find out how to pass the haptics data to connected DualSense controllers

**Comment by streetpea** [comment]
Thanks for starting to look into this @jbaiter … as for steamworks that is something we would have to get permission from @thestr4ng3r to use because it violates the gpl license (see https://partner.steamgames.com/doc/sdk/uploading/distributing_opensource) so if there is a way to do this without using steamworks that would be preferred.

**Comment by jbaiter** [comment]
I think there's a way, did some googling and it seems you can talk directly to the haptics without going through the steamworks library, e.g. https://github.com/Roboron3042/SteamControllerSinger.
In other news, I got some starting help from @thestr4ng3r and am now knee deep in implementing haptics and trigger effects for DualSense controllers attached via USB, it's probably going to take a while, but I think I'll get there :-)))

**Comment by Entropy512** [comment]
As far as the Takion side of things - I haven't really tested it much, but in theory pyremoteplay now supports haptics - https://github.com/ktnrg45/pyremoteplay/compare/master...rumble

**Comment by jbaiter** [comment]
> As far as the Takion side of things - I haven't really tested it much, but in theory pyremoteplay now supports haptics - https://github.com/ktnrg45/pyremoteplay/compare/master...rumble

That's only for the DS4 rumble emulation, not for the 'real' haptics, Chiaki already supports that.

As for the 'real' haptics, I managed to get them working just a few moments ago. Current requirement is using the `pipewire` audio driver for SDL, but that should not be a problem on the Deck, since it's using that for Audio handling anyways, afaik.
PR will be forthcoming after I clean up a bit and investigate a small edge case with trigger effects in Astro's Playroom (can't hold onto the 'weak' handholds in the climbing minigame where you have to pull the trigger halfway).

**Comment by streetpea** [comment]
Awesome work @jbaiter! 

I agree that libusb or hidapi is the way to go if not using SteamInput. This is also required for the gyro bc it’s not exposed via sdl or evdev for the Steam Deck. The negative of this is it requires sudo (normally not a big concern but requires setting a password on Steam Deck which frightens some users) for access (not a problem for DualSense because the udev rules for gyro/touchpad w/ evdev already require sudo but it would now require sudo even if people don’t use the DualSense). While this is a concern, it seems like it’s the only way at the moment based on what’s exposed outside of Steam Input so is the best (potentially only) path forward. 

Any software dependencies that need to be added (such as pipewire) if not already included in the flatpak can be added to the flatpak container during build. 

As far as haptics for the Steam Deck controller, how would it switch between simulated haptics for rumble and “real” haptics or do fake haptics get sent for ps4 games too and we can still use those for ps4 games? As far as the pcm to pwm, [Here is an example](http://www.aidanmocke.com/blog/2018/11/19/pwm-audio/) of someone trying this in a different project but I’m not sure how much help it will be.

**Comment by jbaiter** [comment]
> As far as haptics for the Steam Deck controller, how would it switch between simulated haptics for rumble (what it’s doing now) and “real” haptics or do fake haptics get sent for ps4 games too and we can still use those for ps4 games? As far as the pcm to pwm, [Here is an example](http://www.aidanmocke.com/blog/2018/11/19/pwm-audio/) of someone trying this in a different project but I’m not sure how much help it will be.

On the API level, rumble events are sent through SDL's gamepad routines to the HID device, while Haptics are sent as audio samples to the DualSense Audio device. When sending a rumble signal, SDL sets some bits to disable audio haptics, which are then cleared once the rumble effect is disabled. When emulating the rumble and haptics through the Steam Deck's touchpads, I think we can follow the same approach, use SDL for regular rumble, and direct USB access for the haptics. They will with large certainty never interfere with each other, since games that use rumble don't use haptics, and vice versa.
Thanks for the link, I'll take a look!

**Comment by ejleslie** [comment]
Jumping back in only because I saw that @jbaiter is also contributing over on the main chiaki repo - will haptics and adaptive trigger support for Dualsense be coming to the Win64 build of chiaki? Because holy crap, that would rule.

**Comment by jbaiter** [comment]
It sure will!
If you want to help, you can beta-test the feature by downloading the build here and reporting back (via e-mail, windows is probably out of scope for this issue) if it works for you :-)
https://ci.appveyor.com/api/buildjobs/tw8xu4p3hv02hv52/artifacts/Chiaki.zip

**Comment by ejleslie** [comment]
I absolutely will. 🙂

**Comment by streetpea** [comment]
As per the discussion in #7, I have the some questions for when I start work on playing the files / inputs you get from the PS5 using the Steam Deck haptics using the play haptic functionality from my hidapi code.

Once I start that effort, a sample haptic file would be nice for testing. As for the trigger effects, is that something that you know when you get it and can then play the appropriate haptic or does it work some other way? Also, how does this work with the sound output haptics? Are you guaranteed to only get one at a time or does one take precedence over another? Based on the files you provided, it seems like these effects would be something we would provide a specific function for and trigger at the appropriate time. Is this what you had in mind?

**Comment by jbaiter** [comment]
> As for the trigger effects, is that something that you know when you get it and can then play the appropriate haptic or does it work some other way?

Yes, it's simply a discrete packet sent over the Remote Play protocol that tells you which effect to send to the triggers, just like rumble. The data is basically sent as-is (with some rearranging) via HID (or rather, via SDL2, which has an API for that) to the DualSense.

> Also, how does this work with the sound output haptics? Are you guaranteed to only get one at a time or does one take precedence over another?

Those two are completely independent. Trigger effects are discrete events, haptic effects are implemented as a semi-continuous audio stream, just like the regular video and audio streams. "Semi-continuous", because silence is not encoded explicitly, i.e. when there are no haptics, no data is sent. The handling of those two is completely separated as well, there's no relationship at the protocol or application level between them. Haptics are resampled from 3KHz to 48KHz and sent as raw PCM to the DualSense audio device, separate from the HID stack.

>  Based on the files you provided, it seems like these effects would be something we would provide a specific function for and trigger at the appropriate time. Is this what you had in mind?

If we decide to map both the trigger effects *and* the regular haptics to the Steam Deck's haptics, we're going to need to interleave the two sources somehow, probably with a queue and some prioritization heuristics.

It's probably wiser to leave that for later and start with mapping only the haptics first :-)

Links to relevant code sections:
- Receiving trigger effects: https://git.sr.ht/~jbaiter/chiaki/tree/gui-haptics/item/gui/src/streamsession.cpp#L548-559
- Sending trigger effects to controller: https://git.sr.ht/~jbaiter/chiaki/tree/gui-haptics/item/gui/src/controllermanager.cpp#L337-352
- Setting up haptics reception: https://git.sr.ht/~jbaiter/chiaki/tree/gui-haptics/item/gui/src/streamsession.cpp#L150-155
- Setting up haptics audio system: https://git.sr.ht/~jbaiter/chiaki/tree/gui-haptics/item/gui/src/streamsession.cpp#L420-448
- Connecting a controller to the haptics: https://git.sr.ht/~jbaiter/chiaki/tree/gui-haptics/item/gui/src/streamsession.cpp#L458-490
- Receiving haptics and sending them to the controller: https://git.sr.ht/~jbaiter/chiaki/tree/gui-haptics/item/gui/src/streamsession.cpp#L499-523

**Comment by streetpea** [comment]
I have been working on the Steam Deck haptics. There are limitations to what the Steam Deck haptics can do as opposed to the DualSense (especially since we have to translate the pcm signal on the fly which leads to a trade off between resolution / minimum frequency and latency [though we can cheat the future a little bit]) but the majority of the haptics seem to be working reasonably well though are a bit noisy atm. One thing I ran into was the gpu jungle section of Astro’s playroom where you are the monkey seems to break when using the enable dualsense option. Specifically, when you are climbing it doesn’t let you grab one of the higher ledges. It seems that it’s waiting for a trigger to go to the next stage for the adaptive triggers or something. Not sure if you have seen this @jbaiter? Also, in general have you made any updates to the haptics since the link you posted before? I have been using that to start with but will want to add any changes before the next release.

**Comment by jbaiter** [comment]
This was fixed in a recent commit on my branch, I had flipped the branches on a ternary by accident 🙈
https://git.sr.ht/~jbaiter/chiaki/commit/5c58a6bf525f01f835629bd8a9226d8eb1ac24a8

**Comment by streetpea** [comment]
@jbaiter as far as the hot plugging of the DualSense, I made 2 minor tweaks:
1. changed from using guids to pid/vid since missing some guids resulted in controller working sometimes and not others (since it was random on plugin) [here](https://github.com/streetpea/chiaki4deck/blob/main/gui/src/controllermanager.cpp#L258)
2. Increased timer from 250ms to 1000ms for DualSense hot plug because 250ms sometimes wasn't enough time for haptics audio device to become available (resulting in it not being detected) [here](https://github.com/streetpea/chiaki4deck/blob/main/gui/src/streamsession.cpp#L555)
