### ISSUE TITLE
Flatpack Update Error

### ISSUE THREAD

**Issue by nabel0** [streetpea/chiaki4deck#15]
Hi..If i try to update via Discover Store i get the following Error:

![Screenshot 2022-10-13 201039](https://user-images.githubusercontent.com/50377455/195673947-3ba48c91-7df3-4ae0-9f6a-d454c3dd9046.jpg)

**Comment by streetpea** [comment]
That's weird since that is in flathub and should have been installed with the base flatpak install. Did you try the cli command as well?:

```
flatpak update --user -y re.chiaki.Chiaki4deck
```

Also, all you did was click on the updates button and try to update?

**Comment by streetpea** [comment]
Based on the your initial install (with `flatpak install --user -y https://github.com/streetpea/chiaki4deck/releases/download/v1.1.0/re.chiaki.Chiaki4deck.flatpakref`), you should have the following flatpak remotes (when you run `flatpak remotes`):

```
Name               Options
flathub            system
flathub            user
chiaki4deck-origin user,no-enumerate
```

and the following user-level flatpaks (shown via `flatpak list --user`) [of course you probably have more but this is a minimum]:

```
Name                                  Application ID                                                  Version             Branch                 Origin
Mesa                                  org.freedesktop.Platform.GL.default                             21.3.9              21.08                  flathub
openh264                              org.freedesktop.Platform.openh264                               2.1.0               2.0                    flathub
Breeze GTK theme                      org.gtk.Gtk3theme.Breeze                                        5.26.0              3.22                   flathub
KDE Application Platform              org.kde.Platform                                                                    5.15-21.08             flathub
QGnomePlatform                        org.kde.PlatformTheme.QGnomePlatform                                                5.15-21.08             flathub
QtSNI                                 org.kde.PlatformTheme.QtSNI                                                         5.15-21.08             flathub
QGnomePlatform-decoration             org.kde.WaylandDecoration.QGnomePlatform-decoration                                 5.15-21.08             flathub
Chiaki4deck                           re.chiaki.Chiaki4deck                                           1.1.0               chiaki4deck            chiaki4deck-origin
```

Do you have these on your system? I'm thinking the the user version of flathub might have gotten deleted. (i.e., in the `flatpak remotes` output, **flathub     user** isn't listed). Since `chiaki4deck` is installed as a user flatpak it uses the user-level installs. This, if there is no user flathub configured it won't be able to find the flathub repositories which would cause your issue. Of course, that's just one possibility so seeing if those things are configured for you would be helpful to diagnosing the issue.

**Comment by nabel0** [comment]
You are right..."flathub user" wasn't listed/installed.
This fixed my problems...Thank you very much....
