### ISSUE TITLE
Upload to Flathub?

### ISSUE THREAD

**Issue by dogtopus** [streetpea/chiaki4deck#16]
Flathub is available on most existing flatpak setup. It would make it easier to install chiaki4deck directly from Software/Discover without need to open up a browser.

**Comment by streetpea** [comment]
This is something I need to look into. I agree this would be a better option. Originally, I was planning for the code to be added to the main Chiaki flatpak eventually so this didn’t make sense. However, while some of the additions may be added, I don’t think all of the chiaki4deck features will be added to Chiaki since the author is focusing on keeping the code as concise as possible as opposed to adding new features (except in specific cases). I’ll confirm with @thestr4ng3r that this makes sense. If so, I will pursue this.

**Comment by streetpea** [comment]
The main reason I haven't moved on this is Chiaki is already on flathub and I'm not sure if the fork has enough changes to get accepted based on their guidelines. However, if it does I would submit it to be hosted on Flathub to make the installation slightly easier plus not have to self-host the repo. As far as a package, someone did actually work on packages users could build for Chiaki and chiaki4deck for Steam Deck ... see https://gist.github.com/tvidal-net/dda93291eb5898d43ae268e063c928be so that may be a place to start if you want to look into it @AxelTerizaki.

**Comment by AxelTerizaki** [comment]
Since it has a different name, I think it has its worth. Maybe an icon change might be needed though but I don't know flathub's stance on that. I mean, there's Betterbird, who's a minimal fork of Thunderbird on there. The features added to Chiaki4deck justify its existence, especially since the main project is on maintenance now. :)

Thanks for the link for building, I'll look into it when I'll have some time. I can't promise I'll do it but I'd like to try my hands at my first AUR package with chiaki4deck :)

**Comment by garrett** [comment]
About forks on Flathub:

Flathub does have several forks available at the same time for other apps. For example, DOSBox has 3 different forks:

![Screenshot_20230714-184315](https://github.com/streetpea/chiaki4deck/assets/10246/29da39ae-b9cf-4919-b7d7-b1d197c81e58)

https://flathub.org/apps/search?q=DOSBox

...and there are 18 results for "DOOM". (Some are games based on one DOOM engine or another. Others are various forks with different featuresets, so it's not as straightforward of a comparison as DOSBox, but still relevant.)

https://flathub.org/apps/search?q=DOOM

You definitely would want a different icon, of course.

**Comment by streetpea** [comment]
ok, thanks for the examples @garrett  I'll submit an app request for flathub shortly then.

**Comment by streetpea** [comment]
Update: I submitted it to Flathub for approval [here](https://github.com/flathub/flathub/pull/4332)

**Comment by AxelTerizaki** [comment]
Good luck witht he changes, flathub can be a little strict but it's for a good reason :)

**Comment by AxelTerizaki** [comment]
Since it seems on Flathub now, should the documentation be changed? There are a lot of references to `re.chiaki.Chiaki4deck` there, including the launcher creator script and the launcher itself.
