### ISSUE TITLE
Rabdom tear and grasale

### ISSUE THREAD

**Issue by murdamatt09** [streetpea/chiaki4deck#19]
On latest version and having screen tear. Tried various ps5 settings.

**Comment by streetpea** [comment]
This sounds like you are experiencing wireless performance problems. Have you tried 720p, 30fps settings and deleting the current bitrate (this will make it use the default  instead of a higher configured bitrate) in the settings? For additional options see https://streetpea.github.io/chiaki4deck/setup/configuration/#troubleshooting-performance-issues

**Comment by streetpea** [comment]
This should be improved with release 1.5.0
