### ISSUE TITLE
After updating, my non steam game shortcut for chiaki no longer works

### ISSUE THREAD

**Issue by prime666** [streetpea/chiaki4deck#20]

**Comment by prime666** [comment]
I tried deleting it and re-adding it but it still doesn't start unfortunately.

**Comment by streetpea** [comment]
Is this after updating chiaki4deck or your Steam Deck itself? Also, have you tried restarting your Steam Deck and trying to launch the non-Steam game again?

**Comment by prime666** [comment]
This happened after updating chiaki4deck. Yeah, getting the same issue even after restarting. When trying to launch through steam via game mode it I get the steam loading symbol until it just closes and goes back to the non-steam game screen

**Comment by streetpea** [comment]
Hmm, I haven’t seen this before (updating chiaki4deck causing it to not launch). Does chiaki4deck work outside of Steam? Can you open the game properties for the game in Steam (right click on game and select properties) and tell me what they say for the various things?

**Comment by streetpea** [comment]
I have seen the behavior of the game not launching for non-Steam games when the game name was changed without a restart (Steam bug/limitation) or if proton compatibility was ticked on for a native linux game (user configuration error) but it doesn’t sound like either apply to your situation.

**Comment by prime666** [comment]
I was having the problem before updating, so I updated figuring that was what I needed to do for it to work again. It works via desktop mode, I'm able to start a game and such. When I open properties, the target path is "/home/deck/.var/app/re.chiaki.Chiaki4deck/config/Chiaki/Chiaki-launcher.sh" and the start in path is "/home/deck/.var/app/re.chiaki.Chiaki4deck/config/Chiaki/"

**Comment by streetpea** [comment]
The script listed in the target path works via desktop mode? If that’s the case, then it seems something got messed up with the non-Steam game configuration for the game in Steam. Make sure in the compatibility section of the game properties “force the use of a specific Steam Play compatibility tool” is unchecked as it being checked would cause this issue since you shouldn’t use proton with a Linux native game. if that is unchecked, then it’s possible something got messed up in the configuration of the game itself under the hood. 

chiaki4deck itself doesn’t edit this so this would almost certainly be a Steam bug with the handling of non-Steam game configuration files. The first thing I would try is to add the game as a non-Steam game with a different name and see if that works as a test.

**Comment by prime666** [comment]
My apologies, I didn't try the script itself via desktop mode. When doing that I seem to get multiple errors; couldn't connect to my Playstation console, check that the steam deck and playstation are on the same network, and I have the correct IP address. It sounds like I just need to recreate the automation script? I think I'll try that.

**Comment by streetpea** [comment]
That would fix it if some of the info in the script is wrong. Based on the error, it sounds like the PlayStation ip may have changed. Does the ip in the script match the ip that chiaki4deck shows in the gui?

**Comment by prime666** [comment]
My issue was with my script. I guess my IP for my PS5 changed so the script had an old one. I just edited the values within and that did the trick. Thank you for your help. Shall I close the issue forum?

**Comment by streetpea** [comment]
If you want to prevent this in the future, I would suggest setting a static ip for your PlayStation in your wireless router. Otherwise, your ip could possibly change if your PlayStation is turned off and a different device uses its old ip causing this issue. Usually a hostname would prevent this issue (since the hostname would remain constant while the ip could change), but with home routers most don’t provide hostnames / dns by themselves so this isn’t a suitable option. The UI used broadcast to find the IP but that doesn’t work with remote connections so would break the automation in those situations so for now using an ip or hostname (external connections / vpn that provides hostname if you have it set up) is the best option. I should probably update the doc to mention setting a static ip, since this could happen to other users as well given the PlayStation goes offline for a time and a different device connects.

**Comment by streetpea** [comment]
You can close this issue, since your specific issue is resolved. I created issue #21 to address the documentation update for static ip recommendation.

**Comment by prime666** [comment]
I'm looking into setting up a static IP for it right now, but as you said, it's a bit finicky with different routers. But I definitely would prefer not having to update the script anymore

**Comment by streetpea** [comment]
Here is an example for a few different routers I found via Google. Not sure if that covers yours or not but may be helpful.

**Comment by prime666** [comment]
That article is great, it covered everything I did for a netgear router. I'm not sure if you'd know whether or not its effective, but my router has ipv6 turned off by default, but I heard having it on can be beneficial for newer devices i.e. the steam deck and such. Should I look into enabling it?

**Comment by streetpea** [comment]
Are you referring to ipv6 or wifi6? Wifi6 (802.11 ax) gives better performance for newer devices vs. Wifi5 (802.11 ac). Only newer devices support Wifi6 (802.11 ax) and this is likely what people were referring to regarding performance improvements for newer devices (see https://www.minim.com/blog/wifi-4-vs-wifi-5-vs-wifi-6) such as maximum throughput going from 3.5 Gbps to 9.6 Gbps. However, Steam Deck does not support Wifi6 (802.11 ax). According to Steam's tech specs for the Steam Deck (https://www.steamdeck.com/en/tech), the wifi chip only supports up to Wifi5 (802.11 ac), so if you have a Wifi6 router the Steam Deck will be using the Wifi5 backwards compatibility with it, not getting the Wifi6 boost.

As for ipv6 vs ipv4, the main reason for ipv6 is so as to not run out of IP addresses in the future. In general, performance differences are negligible (see https://labs.ripe.net/author/gih/examining-ipv6-performance/, https://superuser.com/questions/181601/is-ipv6-faster-than-ipv4 and https://www.avast.com/c-ipv4-vs-ipv6-addresses#) with some scenarios favoring ipv4 and some scenarios favoring ipv6 but most being similar. Having said that, switching to ipv6 can cause issues with software that isn't able to use ipv6 and in general I wouldn't recommend it yet for a device such as the Steam Deck. If you turn it on and have the option for both that is likely fine if you want, but not needed. I would make sure to keep IPV4 for backward compatibility purposes with software that doesn't support IPV6 though.

**Comment by prime666** [comment]
Ah okay. I was meaning ipv6 but I certainly won't enable just ipv6 thanks to your info. I'll leave both enabled. I really appreciate all your help. chiaki4deck makes remote play feel as good as playing on my ps directly for the most part.
