### ISSUE TITLE
Separate Console and Account to adapt local streaming with wireless controller and remote streaming with wired controller

### ISSUE THREAD

**Issue by Kethers** [streetpea/chiaki4deck#364]
**Is your feature request related to a problem? Please describe.**
Hi, sometimes I use PS5's streaming functionalities for different purpose with different accounts.
1. When I am at home with PS5 and I finish the main story of the game, then I would like to earn trophies via web trophy guides like ProxyPyx etc. At this point, I use laptop to locally streamming PS5 as a window and browser as another window so that I can follow those guides and earn trophies very quickly. PS5 is next to me so it wouldn't be necessary to use a wire to connect DualSense controller to PC, instead I just use a **helper account** for streaming but control my **main account** that earns trophies with wireless controller connection.
2. On vacation when not with PS5, I use remote streaming with wired controller connection to an laptop, with my main account.

So here is the issue: both situation connect to the same PS5 and maybe with same IP address(with ZeroTier or some other tools). I want to streaming with different account but currently chiaki4deck didn't separate the account and console. If I add new console but with different account it will pop up a tip to ask you to overwrite the old config or not, whatever I choose I can't preserve 2 account with same IP address console at the same time. 
Actually now I when I do remote streaming I use chiaki4deck, I use official PS remote play when I do local streaming.

**Describe the solution you'd like**
Separate account info and console info, so as to make it possible to have 2 console with same IP address but different ps account in chiaki4deck

**Describe alternatives you've considered**
A further solution might be account-selectable when choosing a console to connect.

**Comment by streetpea** [comment]
@Kethers you can use the --profile option to have multiple users now

**Comment by streetpea** [comment]
So for your 2nd user use --profile=user1 or whatever you'd like instead of user1 in the shortcut you create (you can create a Steam shortcut using the option on the main home menu of Chiaki4deck and for launch options add --profile=user1 for the shortcut using the 2nd user) then launch Chiaki4deck via that shortcut and register the console using that shortcut. Then, when you open that shortcut and connect to the console it will be with that user. Use your regular shortcut for the other user. You can create as many different shortcuts you want with with different profiles for more users.
