### ISSUE TITLE
Chiaki-launcher.sh not working when external network is set up

### ISSUE THREAD

**Issue by xCISACx** [streetpea/chiaki4deck#40]
I can open the regular flatpak version of Chiaki fine by itself and even connect to my PS4 Pro outside my home network using the external IP (testing with my phone as a hotspot for the Steam Deck).
I added it manually using the external IP, my ID and the PIN and it opens just fine when connected to my hotspot.

However, when I try to set up that exact same external IP using the script configurator through Konsole, the resulting Chiaki-launcher.sh refuses to launch from outside my network, only working when I'm connected to my home network.
It doesn't work when running it directly from the folder, nor through Steam.
Steam also thinks Chiaki4Deck is running and it won't close it, forcing me to restart Steam.
I get no error.
When it does manage to close it after some time, I get no new logs in the logs folder so I can't provide any.

I'm not sure what the problem could be as it's the exact same IP.
Seems like a bug but it might also be user error.

I just updated Chiaki4Deck to the newest version (1.3.1) using Discover and the issue still persists.

Any help would be appreciated.
Let me know if I need to submit any files.
Might be related to: https://github.com/streetpea/chiaki4deck/issues/25

EDIT:

Managed to get a log by running it through Konsole:

`"${HOME}/.var/app/re.chiaki.Chiaki4deck/config/Chiaki/Chiaki-launcher.sh"
Error: Couldn't connect to your PlayStation console from your external address!
Error: Please check that you have forwarded the necessary ports on your router
Error: ...and that you have the right external PlayStation IP address or hostname!
 `
 
This doesn't make sense as I used the exact same external IP and it works through the non-automated app.

Attached are two logs proving I can connect both locally and externally using the app but not the script.

[chiaki_local_session_2023-01-20_05-06-11-971971.log](https://github.com/streetpea/chiaki4deck/files/10463371/chiaki_local_session_2023-01-20_05-06-11-971971.log)
[chiaki_external_session_2023-01-20_05-03-01-976976.log](https://github.com/streetpea/chiaki4deck/files/10463372/chiaki_external_session_2023-01-20_05-03-01-976976.log)

**Comment by streetpea** [comment]
I don't believe it's related to #25 as that is an issue when the application itself is starting. You're having an issue before it gets to launching the application. Specifically, it seems like the following command is failing for you:
```
flatpak run re.chiaki.Chiaki4deck discover -h ip_addr
```
where `ip_addr` is your PlayStation's ip address. Can you try running that command in your console by itself?

**Comment by xCISACx** [comment]
Should I use my local or external IP? 
I am currently not home so I'll try with the external.
If it is my local IP, I will try it later on.

**Comment by xCISACx** [comment]
Using the command requested for my external IP from an external network:

```
[I] Discovery failed to bind port 9304, trying one higher
[E] Discovery request timed out after timeout: 2.0 seconds
```

From my home network with the local IP it works and says the following:

```
I] Discovery failed to bind port 9304, trying one higher
[I] --
[I] Discovered Host:
[I] State:                             ready
[I] System Version:                    10010001
[I] Device Discovery Protocol Version: 00020020
[I] Request Port:                      997
[I] Host Name:                         PS4-160
[I] Host Type:                         PS4
[I] Host ID:                           C863F18F5C39
[I] --
```

I'm not sure why it fails to bind when that port is open.

My PS5 works flawlessly either way so it seems to be an issue exclusive to my PS4 Pro.
I won't be using the PS4 anymore so the issue won't affect me anymore thankfully.
I'm not sure I can help debug why it happens on the PS4 further however.
Let me know if you need more logs or want me to test something.

**Comment by streetpea** [comment]
Do you have the gui open? It may be using 9304 which is why you have to go one higher. That’s probably a red herring though as that’s on your Steam Deck.

**Comment by xCISACx** [comment]
Oh, I did have the GUI open while running Konsole so that might be why.
But yeah, it doesn't seem to be related because the PS5 logs say the same and it connects anyway.

**Comment by streetpea** [comment]
Hmm so the ps4 and ps5 use different discovery ports, maybe it’s related to that. Can you confirm both of the ports are/were forwarded: 987 udp and 9302 udp?

**Comment by Serg86** [comment]
I have the problem that the script does not work on my external IP, because discover always times out, I am unable to get any sort of response via my external IP from my PS4 through the script.

I added my PS4 manually in the GUI via external IP, wake up works (with ports open), connecting works through the GUI. As a workaround I modified the script and moved the code which relies on discover into the "if on local Wifi" brackets, and just added the wake up command and a simple sleep 20 to the external bracket for the time being.

I tried to increase the discover timeout up to 60 seconds, open many different ports, even every port in the range 800-20000, putting the PS4 in the DMZ in my router, disabling router firewall entirely, the discover command always times out.

Is the discover command supposed to work on external IP?

**Comment by pedroteosousa** [comment]
@Serg86 did you find anything else about this? I also tried a bunch of stuff and nothing worked. When I run the discover command to my IP from outside my network and make the UDP port-forwarding to another computer instead of my PS4 I do receive a discovery request on port 987, so I believe the PS4 is receiving it too, but I am not 100% sure. But just like you, I only get timeouts.

**Comment by pedroteosousa** [comment]
If you open port 987 with `nc -ul -p 987` and make the port forwarding on your router, when you run the chiaki4deck discover command to your public IP the device does receive the discovery command. If you then type anything on the netcat prompt the deck discover command says that it received an invalid response, so it is able to receive the response back.

Given this, the problem seems to be that the PS4 is "ignoring" discovery requests when the requester's IP is from outside the local network, but I am not sure, and I don't know how to test this either.

**Comment by streetpea** [comment]
That's strange. Unfortunately I don't have a ps4 to test this with but I wonder if it has to do with the fact it's using port 987 instead of one of the higher ports outside of the reserved range.

**Comment by Serg86** [comment]
It's on Ethernet on my end and remote wake up works fine, it's the discover command which does not. Like I mentioned above, I rewrote the script to no longer rely on the discover command for external IP, but simply added a timer before attempting to connect via external IP and it works*.

*Apart from the issue where it says Remote Play has crashed on the PS4 and I can't connect until I restart it, but that is a different issue altogether and seems to affect mainline Chiaki as well.

**Comment by LilDooDoo** [comment]
I'm having the same issue where connecting non the same network works both through the app and through the script, but connecting remotely only work through the app. When I try to run the script on a different network the console tells me to check that I've typed in the correct external IP-adress, even though I've typed in the same one I've entered in the program.

**Comment by streetpea** [comment]
Ok so it seems like from all of the above comments that discovery doesn't work with a remote network on PS4. This means the script needs to be changed for remote network on PS4 to not use discovery and instead use a different (I.e., less precise) method. I'll update the script to do this in the next update.
