### ISSUE TITLE
Disable haptics with multiple controllers

### ISSUE THREAD

**Issue by cgarst** [streetpea/chiaki4deck#44]
In the use case where the steam deck is configured for experimental settings, and is connected to a television with an external controller paired, the deck will buzz away on the TV stand while playing. 

A nice feature would be the ability to toggle haptics off when multiple controllers are detected.

**Comment by streetpea** [comment]
Right now if experimental features are enabled haptics will be routed to the dualsense if plugged in or else to the deck (if using the Steam deck). I think it’s a good idea make it so that if a controller is connected the Steam Deck haptics turn off by default or the user at least has an option for this.
