### ISSUE TITLE
Question not an issue

### ISSUE THREAD

**Issue by iTsMute** [streetpea/chiaki4deck#49]
Sorry for asking this here, just don't know a better place to ask. I use windows on my deck not steam os. I'm currently using chiaki and was interested in trying out chiaki4deck. I was wondering if it will work on windows for the deck? If so do I just need to download the 1.3 version zip? Also do I need to Uninstall my current chiaki? Thanks

**Comment by streetpea** [comment]
There is no windows build at this time. There isn’t anything really linux specific but I or someone else would have to go through the process of making a build for windows and distributing it somehow and since most ppl are using steamOS and I personally don’t have windows on my Steam Deck it hasn’t been done yet.

**Comment by streetpea** [comment]
closing as this was just a question that's now been answered
