### ISSUE TITLE
[Feature Request] Invert gyro response

### ISSUE THREAD

**Issue by szszoke** [streetpea/chiaki4deck#54]
Hello!

It would be really useful if the individual gyro axes could be inverted.

One game where this would be relevant for me is Horizon Forbidden West which has support for gyro aiming but has no support for inverting the response for roll.

I typically use yaw when I'm playing on a TV but I found that roll works better for a handheld like the Steam Deck. It just.. turns the "wrong" way.

**Comment by streetpea** [comment]
@szszoke so it depends on the game whether or not roll turns the "wrong way". In some games it works properly (such as Astro's playroom as seen in the controller demo) and in others it doesn't. It seems like the issue isn't roll turning the wrong way per se. It's that roll itself isn't being used for motion. Instead it's using yaw and acceleration changes that expect a specific orientation. Thus, even if I invert roll, it still "turns the wrong way" in-game for multiple games because the issue seems to be it's not using roll in the desired way and it expects a different controller orientation. In other words, unless you change the acceleration / orientation and use roll as the movement response (replacing yaw for roll) you don't get the behavior you want. Thus, just inverting roll isn't useful (at least from my testing when I tried that I get rotational drift since the angular velocity (in this case roll) doesn't match with the changes in acceleration/orientation values). Can you please try the vertical orientation option in the recent update and see if that behaves as you want, since that allows you to use roll like it seems you want. Lmk if that solves your issue.

**Comment by streetpea** [comment]
I believe the vertical orientation solves this issue. If not please reopen.
