### ISSUE TITLE
chiaki4deck wrong input/layout

### ISSUE THREAD

**Issue by NightwingRed** [streetpea/chiaki4deck#55]
Hi! From the beginning, i have the wrong layout while using Remote Play. For example:
A - X, Left trigger L2 also X button. 
B, both menu buttons and left trigger L2 response as PS button. Do you have any tips to fix it?
I added a community layout, but it just didn't work at all.
L5 is set to End session but it works like a command on desktop mode. 
thanks

**Comment by streetpea** [comment]
@NightwingRed  are you in game mode and using the [chiaki4deck+ default controller layout](https://streetpea.github.io/chiaki4deck/setup/controlling/#default-controller-profile)? If in desktop mode (as you mentioned) you have to go into the settings and make sure you are using the correct controller profile for that (though I would recommend using game mode since it's a better experience in general),

**Comment by NightwingRed** [comment]
@streetpea I always use game mode, but Steam Deck swaps me into desktop mode while I am using it, I think. It finally worked! I just set the layout in desktop mode and it's worked. Game mode and desktop. Thanks for tip and you support!
