### ISSUE TITLE
Flatpakref file has a space at the end of the final line which caused issues in installation

### ISSUE THREAD

**Issue by VikingSchism** [streetpea/chiaki4deck#56]
I was trying to install the project earlier today and was getting an error when attempting to run the command from the documentation:

![](https://cdn.discordapp.com/attachments/960114553495093249/1091855021131431976/image.png)

Out of curiosity I downloaded the flatpakref file and took a look at contents and found a space at the end of the final line (with the URL referring to flathub). Removing this final space caused the install to work upon reattempting.

**Comment by streetpea** [comment]
@VikingSchism thanks for letting me know, were you using Steam Deck or Manjaro? It worked fine for me before on Steam Deck (though I guess it could have broken with a SteamOS update) but it was broken on Manjaro due to the space at the end of the last line like you mentioned. I took out the space and re-uploaded the file and it seems to work now. Let me know if this fixes it for you as well.

**Comment by VikingSchism** [comment]
It was on Manjaro, yes - it seems like it is working like that now from the Github link. Thanks for the fix
