### ISSUE TITLE
win version support

### ISSUE THREAD

**Issue by SemonCat** [streetpea/chiaki4deck#61]
since the origin chiaki not support DualSense,

is there has any chance that this repo can also build win version?

**Comment by streetpea** [comment]
As of release 2.2 Chiaki now supports Dualsense haptic feedback and adaptive triggers.

**Comment by Onkeyuk** [comment]
I’m sure I remember this having touchpad support when I had a deck. I’m not in a windows handheld. Any chance if a windows version with touchpad support?

**Comment by streetpea** [comment]
As of version 2.2 Chiaki has touchpad support for attached controllers that expose their touchpad thorough SDL such as a Dualsense. This doesn't include Steam controllers because they don't expose their touchpad via SDL. I also added the ability to use touchscreens as a touchpad in chiaki4deck. That isn't currently available in Chiaki but I made a pull request for this in Chiaki so it should be available in the future.

**Comment by Onkeyuk** [comment]
That’s fantastic if it makes it into the main batch and ends up in windows. Thanks!

**Comment by streetpea** [comment]
windows version is now available on the releases page [here](https://github.com/streetpea/chiaki4deck/releases/download/v1.4.1/Chiaki4deck-win_x64-VC-Release.zip).

**Comment by Onkeyuk** [comment]
Thank you very much @streetpea this is awesome.
