### ISSUE TITLE
issue with gyro/accelerometer using chiaki4deck

### ISSUE THREAD

**Issue by Bazookasstoo** [streetpea/chiaki4deck#66]
Hi,
i would like to play games like in famous second son !
the gyro works fine when you have to paint with bomb !
but we need to shake the bomb (in fact shake the DS4) !
with chiaki don't work ! no shake ! (shake the deck)
works fine under windows with steam deck tools ans ds4 program!
Is there a solution under steamos linux ?
Future update ? problem with accelerometer ?
Thanks a lot

**Comment by streetpea** [comment]
I'd have to try that specific game to test but there is accelerometer, gyro and orientation data all getting sent to the ps4/5 so I'm not sure what is causing the issue there.

**Comment by rattboi** [comment]
I may be having a similar issue with the game Beyond Two Souls

**Comment by streetpea** [comment]
@rattboi just to check you have the gyro set to as mouse or as joystick in Steam input (it needs to be set for the Steam Deck to send gyro data - use as joystick if you want gyro for games that don't have it by default use as mouse if you only want gyro in games that use it natively within the game)

**Comment by rattboi** [comment]
Indeed, I did use your profile, and since it has native motion controls, I
set it to mouse. I also set it to gyro always on instead of when right
analog is in use.

**Comment by streetpea** [comment]
Ok I'll look into it. Can you please describe your issue..expected behavior and observed behavior as well as where in the game this is?

**Comment by rattboi** [comment]
It's early in the game.

 https://www.youtube.com/live/l9rTnSqzjGk?si=Ts_uAwRRR0uf35zg

15 minutes in, you can possess a guard and when you need to stop possessing
him, it shows to lift the controller in an upward motion. No amount of
shaking and moving had any effect.

I have played the previous game by this studio (heavy rain) and it has a
lot of move and shake controls. I played the PC port of that one on steam
deck and it worked there, of course. I suspect the heavy rain ps4 port on
this collection will also have motion controls problems.

**Comment by streetpea** [comment]
@rattboi I was able to replicate the issue with beyond: two souls. The issue is that the accel values don't go as high with the Steam Deck as with the Dualsense because the Dualsense is lighter so the same force results in higher acceleration than with the Steam Deck. So the amount of force required to trip the switch for the game isn't being registered. If I increase the accel value on the Steam Deck with a multiplier it works. I'll post an update that does this in a few days.

**Comment by rattboi** [comment]
Awesome, thank you so much!

**Comment by rattboi** [comment]
Just curious, is it a manual process from tag -> release -> flathub?

I work in SRE/Platform Engineering, so CI/CD stuff is my wheelhouse. Would you want any help automating these steps?

**Comment by streetpea** [comment]
@rattboi the tag to release to flathub is manual but the builds themselves on Flathub are automated. So right now I just make the tag, release it and make a commit to flathub updating the commit to build to the commit of the release and it builds it. Once it passes the build, I merge it and then it gets released the next day. It should have been out today since I committed the update yesterday but the automated build process failed on the merged branch despite succeeding before merging. It seems like this was a temporary snafu since the error happened while preparing the worker for the build in the Flathub pipeline

**Comment by streetpea** [comment]
If you want to download the fix in the meantime there is a test build from when it did complete successfully with: 
```
flatpak install --user https://dl.flathub.org/build-repo/57111/io.github.streetpea.Chiaki4deck.flatpakref
```

**Comment by streetpea** [comment]
Version 1.4.1 is now available on flathub.
