### ISSUE TITLE
Stretch/Zoom Not working

### ISSUE THREAD

**Issue by FrankFioretti** [streetpea/chiaki4deck#71]
I am using the latest release and the recommended controller layout. I have even tried deleting and recreating the bindings but no matter what, R4/5 do nothing.

**Comment by streetpea** [comment]
Have you done the automation section? (If not you need to go fullscreen using F11 or double clicking either via double tap of screen or using the shortcut as mentioned in the docs). 

If you do the automation section (see https://streetpea.github.io/chiaki4deck/setup/automation/) and run the script in step 3 it will ask if you want stretch, Fullscreen or zoom. If you do the manual version of the automation it will have you do this manually. Since it’s expected for you to go through the different setup sections it should just work at that point. If for some reason you just skip that section (there is a disclaimer at the top of the section linking to the additional steps) which are pointed out in the link I have above. The problem is there isn’t really a good place in the guide to put it so I just put it there.

From the guide: https://streetpea.github.io/chiaki4deck/updates/done/#3-view-modes-for-non-standard-screen-sizes

If for some strange reason you want to launch chiaki4deck via the GUI instead of the automation (not recommended due to the items noted [here](https://streetpea.github.io/chiaki4deck/updates/done/#enabled-automated-launch)), it launches by default in a window matching the aspect ratio of the stream (i.e., 16:9). This means that the stream output exactly matches the stream window. In this scenario, there is nothing to stretch or zoom the stream output to because the stream output already perfectly matches with the stream window. If you want to stretch or zoom, you would need to first either:

>Adjust the window to a bigger or smaller size with your mouse in Desktop Mode (perhaps you want to use chiaki4deck as half of your screen in Desktop mode)
  OR
  Use fullscreen mode by:
  Pressing F11 (either directly in Desktop Mode or via a controller mapping in Game Mode)
  OR
  Double clicking on the screen in Desktop Mode
  Then, you could use stretch and/or zoom accordingly (i.e., Ctrl+S / Ctrl+Z or button mapped to them in game mode).

**Comment by FrankFioretti** [comment]
Thank you and my apologies. I hadn’t read through the automation section so I was unaware it was related. I’m all set!
