### ISSUE TITLE
Can't find official Steam Input controller layout

### ISSUE THREAD

**Issue by LilDooDoo** [streetpea/chiaki4deck#81]
Like the title says, I couldn't find any controller layout by gmoney23. I did however find a couple different layouts by diffeeent users all named chiaki4deck+, which seemed to be pretty much the same. Has gmoney23 by any chance changed their handle?

**Comment by streetpea** [comment]
I do have a controller layout named chiaki4deck+ by gmoney23 in my community layouts tab (checked today). Having said that, someone else mentioned this issue to me and a workaround was to share a personal save steam://controllerconfig/3030286682/3032932469 ... this is also named chiaki4deck+ copy by gmoney23.

Someone also mentioned this bug here: https://steamcommunity.com/app/1675200/discussions/0/3812911294780572967/ ... it may be worth making an issue with valve to see if they can get to the bottom of this.

**Comment by e-t-l** [comment]
> I do have a controller layout named chiaki4deck+ by gmoney23 in my community layouts tab (checked today). Having said that, someone else mentioned this issue to me and a workaround was to share a personal save steam://controllerconfig/3030286682/3032932469

@streetpea is there any way to access/download the layout from a normal web browser? I'd like to fork it but have no idea how. @gmoney23 has no public GH repos

**Comment by dEEkAy2k9** [comment]
This is still a thing!
I just tried setting everything up for chiaki4deck and the only configuration i find is not from gmoney23 but dbfox

There is another layout available

J.Price!
chiaki4deck+ mic
Streatpeas's official chiaki4deck layout w/ mic button mapping

This one seems to get the mappings right as the grip buttons have that control + z stuff BUT it doesn't work.

Just woke up my PS5, got a connection, logged in with pin etc. I was on the PS5 home screen and could select things but the grip buttons didn't do anything. Pressing the left touchpad maximized/minimized the streams window instead of sending the PS Button command. Touchpad did nothing too.

Is something wrong if used via desktop mode?

**Comment by DrewRWx** [comment]
It still seems that the controller layout referenced in the generated Steam app is wrong and switches to the default mapping.

**Comment by streetpea** [comment]
@DrewRWx this issue was from before the create Steam shortcut button in chiaki-ng existed. It was closed after that since then ppl didn’t need to look up the shortcut anymore (which bugged out for some users and showed up for others) and instead could directly add it via its link. It’s worked since then. However, I guess it’s possible that it’s expired or something.
