### ISSUE TITLE
Failed to Initialize Stream on ROG Ally

### ISSUE THREAD

**Issue by drowhunter** [streetpea/chiaki4deck#90]
Failed to initialize Stream Session: Failed to initialize FFMPEG Decoder
[!] Using hardware decoder "vulkan"
[E] avcodec_get_hw_config failed

**Comment by drowhunter** [comment]
i also tried dxva2 and d3d11va

**Comment by streetpea** [comment]
Vulkan won't be supported for hw decoding until ffmpeg 6.1 even though it shows up as an option. Does it work with none selected?

**Comment by streetpea** [comment]
On my windows machine using the chiaki4deck release dxva2 and d3d11va both work while Vulkan fails with the error message failed to initialiaze ffmpeg decoder Vulkan. Since Vulkan won't be supported for hw decoding until ffmpeg 6.1 (currently on 6.0) will have to wait for 6.1 to release for Vulkan support but the other 2 should work.

**Comment by streetpea** [comment]
@drowhunter On my windows machine using the chiaki4deck release dxva2 and d3d11va both work while Vulkan fails with the error message failed to initialiaze ffmpeg decoder Vulkan. Since Vulkan won't be supported for hw decoding until ffmpeg 6.1 (currently on 6.0) will have to wait for 6.1 to release for Vulkan support but the other 2 should work.

**Comment by drowhunter** [comment]
yeah I got this version to work on the ally.

**Comment by streetpea** [comment]
@drowhunter are you good to close this issue then or is there something else you needed?
